# Generated by Django 2.1.4 on 2018-12-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='music.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_price', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.Disc')),
            ],
        ),
        migrations.CreateModel(
            name='Subgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Disc')),
                ('genere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Genere')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('apikey', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='UserHasComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.User')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.User'),
        ),
        migrations.AddField(
            model_name='disc',
            name='genere',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='music.Genere'),
        ),
        migrations.AddField(
            model_name='comment',
            name='disc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.Disc'),
        ),
    ]
