# Generated by Django 2.1.4 on 2018-12-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20181224_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='genere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='music.Genere'),
        ),
    ]
