# Generated by Django 2.1.4 on 2018-12-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20181224_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disc',
            old_name='subgenere',
            new_name='subgeneres',
        ),
    ]
